<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GenusRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class GenusRepository extends EntityRepository
{
    public function findAllPublishedOrderedByRecentlyActive()
    {
        return $this->createQueryBuilder('genus')
            ->andWhere('genus.isPublished = :isPublished')
            ->setParameter('isPublished', true)
            ->leftJoin('genus.notes', 'genus_note')
            ->getQuery()
            ->execute();
    }
}
